base_marker_id: Channel703
head_marker_id: Channel704
freq: 50
kp_x: 0.5
kp_y: 0.5
kp_z: 0.5
kp_r: 0.0
kp_p: 0.0
kp_w: 0.5
ki_x: 0.02
ki_y: 0.02
ki_z: 0.02
ki_r: 0.0
ki_p: 0.02
ki_w: 0.0
kd_x: 0.3
kd_y: 0.3
kd_z: 0.3
kd_r: 0.0
kd_p: 0.0
kd_w: 0.3
